### ISSUE TITLE
021:Wiki - editar

### ISSUE THREAD

**Issue by aslheyrr** [degreeworkunivalle/Front#12]

**Comment by mb3rn4l** [comment]
esto no esta hecho, no lo veo

**Comment by aslheyrr** [comment]
:OKAY:

**Comment by mb3rn4l** [comment]
Si solo quiero editar el titulo no me deja me dice q hay un campo vacio (me parece q es el del contenido q lo indica asi)

**Comment by mb3rn4l** [comment]
Lo del titulo ok 
varias cosas:
1. si un admin edita el request sigue apareciendo , deberia ser como en crear q el request no aparece
2. en lo de rechazar u aprobar dice global name 'e' is not defined

**Comment by aslheyrr** [comment]
Solucionado.
PD: syncdb

2015-09-12 0:53 GMT-05:00 donberna notifications@github.com:
