### ISSUE TITLE
Plan field at Register login is throwing a keyError

### ISSUE THREAD

**Issue by aslheyrr** [degreeworkunivalle/Front#37]
Plan field has been removed ( for now )

**Comment by mb3rn4l** [comment]
en ajustes el campo funciona normal, no se en el registro porq no esta el campo

**Comment by mb3rn4l** [comment]
Esta funcionando normal, el problema es cuando el formulario se envía sin un programa seleccionado

**Comment by aslheyrr** [comment]
eso se soluciona breve, solo tiene que verificar si el campo está vacio
cuando hace el submit, si está vacio solo remueve el campo (remove()) y
luego que siga el flujo normal (ver campo foto en settings)

2015-09-06 14:54 GMT-05:00 donberna notifications@github.com:
