### ISSUE TITLE
Special chars throw exception in wiki slug

### ISSUE THREAD

**Issue by aslheyrr** [degreeworkunivalle/Front#38]

**Comment by mb3rn4l** [comment]
http://www.etnassoft.com/2011/03/03/eliminar-tildes-con-javascript/

**Comment by mb3rn4l** [comment]
Si la url va acompañada de caracteres alfanumericos funciona de maravila, pero si la url es solo caracteres especiales dice q el campo esta en blanco
(No creo q nadie vaya a ser tan ocioso de crear una url asi )
ut me dira si la cierro o no

**Comment by aslheyrr** [comment]
jajajjajaja nunca falta el #polo
por mi no hay problema en cerrarla
