### ISSUE TITLE
Campo foto está como obligatorio

### ISSUE THREAD

**Issue by mb3rn4l** [degreeworkunivalle/Front#42]
En User settings la foto debería ser opcional

**Comment by aslheyrr** [comment]
Efectivamente está opcional, ahora el problema es que: cuando tengo una foto ya configurada y edito cualquier otro campo y no envío foto, me reemplaza la foto que tenía inicialmente, es decir, la borra. ¿Se supone que debe funcionar así?, a mí no me parece.

**Comment by mb3rn4l** [comment]
No se supone que debe funcionar asi, a mi parecer cuando se carga la información se por defecto el campo de la foto debería de contener el archivo de la imagen que tiene actualmente asi cuando edite otro campo y no cambie la foto envié la foto que tiene actualmente issue #7  no le parece ?
