### ISSUE TITLE
Evaluaciones, no permitir realizar un quiz q no tiene preguntas 

### ISSUE THREAD

**Issue by mb3rn4l** [degreeworkunivalle/Front#67]

**Comment by aslheyrr** [comment]
Aparece el titulo del quiz y un botón, pero no lleva al quiz

**Comment by mb3rn4l** [comment]
Para hacer el quiz por ahora tiene q seguir estos pasos:
1. ir a quiz admin 
2. ver detalles en el quiz q quiera 
3. empieza 

posdata: tiene q actualizar los requerimientos, porq se modifico cosas de los servicios

**Comment by mb3rn4l** [comment]
Que tiene esta de malo ? a mi me funciona 
![captura de pantalla de 2015-09-08 16 46 41](https://cloud.githubusercontent.com/assets/7197314/9748256/33cc0f9c-5649-11e5-9f4b-7d9f1a374fd5.png)
