### ISSUE TITLE
Evaluaciones -> 'ascii' codec can't encode character u'\xfa'

### ISSUE THREAD

**Issue by aslheyrr** [degreeworkunivalle/Front#76]
Si hay caracteres especiales en algún valor 505 para todo

**Comment by aslheyrr** [comment]
https://github.com/donberna/django_quiz/blob/master/quiz/models.py#L523 cambiar `str(q)` por `unicode(q)`

**Comment by mb3rn4l** [comment]
Pero eso es tocar el modelo y no ps q no lo puedo tocar ?

**Comment by aslheyrr** [comment]
si encuentra otra manera, perfecto. Además, no me diga que no no tocó la
app original

2015-09-14 15:08 GMT-05:00 donberna notifications@github.com:
